name: Priority/Recommendation Issue
description: I disagree with the recommendations made by the addon, based upon a guide or comparison with a Raidbots sim of my character.
labels: [recommendation, triage]
assignees:
  - Hekili
body:
  - type: checkboxes
    id: precheck
    attributes:
      label: Before You Begin
      description: Please confirm that you've taken these preliminary steps before submitting your issue report.
      options:
        - label: I confirm that I have downloaded the latest version of the addon.
          required: true
        - label: I am not playing on a private server.
          required: true
        - label: I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
          required: true
        - label: I edited the title of this issue (above) so that it describes the issue I am reporting.
          required: true
        - label: I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).
          required: true
  - type: dropdown
    id: flavor
    attributes:
      label: WoW Version
      description: "Reminder: Private servers are not supported based on Blizzard's Terms of Service."
      options:
        - Retail (Dragonflight)
        - Classic (Wrath of the Lich King)
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Describe the Issue
      description: Please describe the issue in question.  Be specific and describe what you see.  You can CTRL+V to paste a screenshot (image) or supply links to screenshot images.
      placeholder: "Example: For my Retribution Paladin, I expect the addon to recommend a Holy Power spender when I have 5 Holy Power.  However, the addon recommended Crusader Strike instead."
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: How to Reproduce
      description: Tell me what I need to do to see the issue you are reporting.
      placeholder: |
        1. Enter game as a Retribution Paladin.
        2. Take the Seraphim, Final Reckoning, and Execution Sentence talents.
        3. Use Final Reckoning.
        4. Build to 5 Holy Power.
        5. See recommendations.
        
    validations:
      required: true
  - type: textarea
    id: player-info
    attributes:
      label: Snapshot
      description: |
        Please supply a Snapshot of the addon's decision-making when you are seeing this issue in-game.  **This is not a screenshot.**  To generate a Snapshot, please complete the following steps.
        * Log into your WoW character.
        * Recreate the issue you are reporting (i.e., generate 5 Holy Power).
        * When you see the recommendation you disagree with, press `ALT-SHIFT-P` to Pause and Snapshot (or use `ALT-SHIFT-[` to Snapshot without pausing).
          * You can change these keybindings in `/hekili` > Toggles if needed.
          * If you take the snapshot at a different time, it will **not** be useful and you'll be asked to submit a new one.
        * Type `/hekili` and press Enter.
        * Open the Snapshots section on the left side.        
        * Select the snapshot that shows the recommendation that you disagree with.
          * Snapshots are labeled with your specialization, the display in question (usually, you'll choose Primary), and the recommendations the addon made with their timings.
        * Click in the `Export Snapshot` box, press `CTRL+A` to select all text *including hidden text*, press `CTRL+C` to copy, then paste into the box below with `CTRL+V`.
        
        This step is essential, as most issues are related to specific classes, specializations, gear, talent choices, or other game systems.
        If you do not provide this information, I cannot triage your problem.
      placeholder: |
        Feral; Primary - Rake(0.00), Scars of Fraternal Strife(1.00), Thrash (Cat)(1.00), Tiger's Fury(1.00), Convoke the Spirits(1.00), Primal Wrath(4.00), Shred(5.00), Shred(6.00), Shred(7.00), Shred(8.00)
        build: 10.0.0-99.1
        level: 60 (60)
        ...
        
      render: Text
    validations:
      required: true
  - type: input
    id: sim-result
    attributes:
      label: Raidbots Sim Report (Link)
      description: |
        The addon's recommendations are based on the SimulationCraft profiles generated for each specialization.  It is very helpful, for testing purposes, to compare the addon's recommendations to your sim's actions.  [Raidbots](https://www.raidbots.com/) is the fastest, easiest way to simulate your character.
        * If the issue happens in single-target, link to your Patchwerk sim with 1 boss target.
        * If the issue happens in sustained multi-target, link to your Patchwerk sim with the appropriate number of boss targets.
        * If the issue happens in more chaotic scenarios, link to your Hectic Add Cleave sim with 1 boss target.
        * You're welcome to link multiple sims using the **Additional Information** box, below.
      placeholder: https://www.raidbots.com/simbot/report/abcdEFghIjKlMNOPqrst
  - type: textarea
    id: addl-info
    attributes:
      label: Additional Information
      description: Please provide any additional information regarding this issue that was not included above.
      placeholder: Leave blank, if all necessary details are included above.
  - type: input
    id: contact
    attributes:
      label: Contact Information
      description: |
        I will contact you via this GitHub ticket with questions and updates.
        If you do not regularly check your GitHub email, please provide an alternate contact method (i.e., Discord ID) so that I can reach you if needed.
      placeholder: Hekili#0001
